### ISSUE TITLE
Question about pitch encoder

### ISSUE THREAD

**Issue by ljh0412** [anonymous-pits/pits#28]
Thanks for interesting paper and nice repo.

I got question about pitch encoder.
In pitch encoder, it takes inputs as ying, spectrogram lengths and speaker embedding.
But its quite wired thing as the encoder get length based mask by common.sequence_mask,
so it should be ying lengths i think.

Is it should be replaced with the parameter?
Please note me to adjust my codes.

**Comment by p0p4k** [comment]
spectrogram lengths and ying lengths are same in this case, since they use same hop-lengths, etc. Each spec frame has a corresponding ying frame.

**Comment by ljh0412** [comment]
> spectrogram lengths and ying lengths are same in this case, since they use same hop-lengths, etc. Each spec frame has a corresponding ying frame.

Thank you for your reply.
