### ISSUE TITLE
Multi-language support?

### ISSUE THREAD

**Issue by Chopin68** [anonymous-pits/pits#3]
Expect to be able to speak multiple languages in one sentence at the same time, which will be a good thing

**Comment by anonymous-pits** [comment]
It is able to apply multilingual scheme as [SANE-TTS](https://arxiv.org/abs/2206.12132), VITS-based multilingual TTS, and apply code-switching like their [demo](https://mindslab-ai.github.io/sane-tts/).
Currently, we do not have plans to release support for additional languages.
However, if you're interested in multilingual support, our pull request is open for contributions.

**Comment by Chopin68** [comment]
Thank you for your timely reply! Looking forward to the release of training code
