### ISSUE TITLE
about training PITS at 44100hz sampling rate 

### ISSUE THREAD

**Issue by innnky** [anonymous-pits/pits#7]
May I ask how can I train PITS at a sampling rate of 44100hz? Following Visinger2's approach,  I have already modified the values of sampling_rate, filter_length, hop_length, win_length, segment_size, ying_hop, upsample_rates, upsample_kernel_sizes, and segment_size in the Avocado discriminator, and have correctly unified the lengths of yingram and spec. Finally, I was able to run the training code. However, the synthesized speech does not sound right. Is there anything else that needs to be modified?

**Comment by anonymous-pits** [comment]
We don't mind training it at 44100 Hz, so I'm not sure about the details. However, I think there may be some alignment issues with the Yingram.

I recommend printing the Yingram calculated in train.py like this:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/125864065/224903762-013971d8-cd46-487f-82fa-b23bbbf5b643.png">

After that change pad value to make it aligned. 
We also suffer same issue like you in the early stage of the research and fix it by changing pad value.
I think that our pad calculation is not scalable now.

**Comment by innnky** [comment]
thanks! i‘ll try it.
