### ISSUE TITLE
What is the role of "tone" in the return value of "text_to_sequence"?

### ISSUE THREAD

**Issue by isletennos** [anonymous-pits/pits#9]
Hello.
In the implementation, the "tone" is embedded and added by "TextEncoder".
This was not the case in the VITS implementation.
What is the intention of this implementation?
Thank you in advance.

**Comment by anonymous-pits** [comment]
Hi [isletennos](https://github.com/isletennos)!
It is from our group's VITS implementation for languages that contain tones, such as Chinese and Mandarin Chinese.

Unfortunately, we are unable to release other language options due to several reasons.

Thank you for your interest!

**Comment by isletennos** [comment]
Okay, I understand.
Thank you.
